spring:
  application:
    name: menu-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${DELIVERY_JWK_SET_URI:http://customer-service:8080/oauth2/jwks}

management:
  endpoints:
    web:
      exposure:
        include: health,info
